import { queueAttempt, queueRhythmTrial, queueSession, queueStroke } from '@/core/db/outbox'
import type {
  AttemptEvent,
  RhythmTrialEvent,
  SessionClock,
  SessionRecord,
  StrokeEvent,
} from '@/core/telemetry/types'

/**
 * The write path for telemetry. architecture.md 6 and rules.md 2.
 *
 * ─── Two rules, both enforced by the shape of these functions ───
 *
 * 1. Every one returns `void`. Not a Promise. A game cannot `await` an emit
 *    inside a `pointerdown` handler, because there is nothing to await. That is
 *    what keeps the network out of the interaction path — and the interaction
 *    path is the thing being measured, so anything added to it is measurement
 *    error.
 *
 * 2. `Date.now()` does not appear in this file. Every `*_ms` value is an offset
 *    from the one `performance.now()` the clock captured at session start. See
 *    the comment at the top of clock.ts for why that matters more here than
 *    almost anywhere else in the product.
 *
 * The uuid v7 for `client_event_id` is generated by the outbox writer, which is
 * also where the Dexie write happens synchronously with the interaction.
 */

/** Timestamps default to "now" so a caller cannot accidentally send a stale one. */
type Timing = {
  presented_at_ms?: number
  first_touch_at_ms?: number | null
  responded_at_ms?: number | null
}

export type AttemptInput = Omit<
  AttemptEvent,
  'client_event_id' | 'presented_at_ms' | 'first_touch_at_ms' | 'responded_at_ms' | 'features'
> &
  Timing & { features?: Record<string, number | null> | null }

export function emitAttempt(clock: SessionClock, input: AttemptInput): void {
  const { presented_at_ms, first_touch_at_ms, responded_at_ms, features, ...rest } = input

  queueAttempt({
    ...rest,
    // Defaulted here so no game has to remember. zod's .nullable() rejects
    // undefined, and a row that fails to parse is quarantined and never syncs.
    features: features ?? null,
    presented_at_ms: presented_at_ms ?? clock.now(),
    // Explicitly null rather than undefined: zod's .nullable() rejects
    // undefined, and a row that fails to parse is quarantined and never synced.
    first_touch_at_ms: first_touch_at_ms ?? null,
    responded_at_ms: responded_at_ms ?? clock.now(),
  })
}

export type StrokeInput = Omit<StrokeEvent, 'client_event_id'>

export function emitStroke(_clock: SessionClock, input: StrokeInput): void {
  // The clock is in the signature for symmetry and to make the dependency
  // obvious at the call site: a stroke's point timestamps are already offsets on
  // this clock's timeline by the time capture hands them over, so there is
  // nothing left to convert here.
  queueStroke(input)
}

export type RhythmTrialInput = Omit<RhythmTrialEvent, 'client_event_id'>

export function emitRhythmTrial(_clock: SessionClock, input: RhythmTrialInput): void {
  // Asynchronies and IOIs stay on the AUDIO clock, in milliseconds, and are NOT
  // converted here. Converting them to the performance timeline would reintroduce
  // exactly the drift the audio clock exists to avoid (architecture.md 6). Use
  // clock.fromAudio() only for the accompanying attempt row's offsets.
  queueRhythmTrial(input)
}

/**
 * Written twice per session: once at start, once at end.
 *
 * At start so an interrupted session still exists — a force-quit halfway through
 * must leave a session row for its attempts to reference, or the whole session's
 * telemetry is orphaned and the flush fails on a foreign key forever. At end to
 * fill in `ended_at`, `completed` and the measured pointer interval.
 *
 * `queueSession` is a put on the primary key, so the second write replaces the
 * first rather than creating a duplicate.
 */
export function emitSession(session: SessionRecord): void {
  queueSession(session)
}
